### ISSUE TITLE
Older images (>3 months) not recognized in compute module resulting in errors

### ISSUE THREAD

**Issue by ervreugdenhil** [oci-landing-zones/terraform-oci-modules-workloads#11]
Previously (Workload <=0.1.6) you could specify an image with an ocid using image.id, even if it is not the most recent one (f.e. the ocid for Oracle Linux 9.4 of May 2024).

As of Workload 0.1.7, (platform) images are retrieved using oci_core_images, which results in errors for older images (>3 months).

I believe this is related to the fact that oci_core_images only gives you a subset of images (the last three versions of major distributions).
- If you look up an image using platform_image.name, older images won't be in this list
- You can provide platform_image.ocid, but some checks are still done based on oci_core_images and will fail (actually it looks like it is the new shape check that is then failing).

Currently, when upgrading from Workload 0.1.6 to 0.1.7 we run into errors as we have Oracle Linux 9.4 of May 2024.
But even if we would use a recent distribution now, won't we run into errors in 3 months? In case we use the name filter, the name will disappear in a few months, and in case we use ocid, the checks won't pass in a few months.

Many thanks for your help!

**Comment by ervreugdenhil** [comment]
Hi @andrecorreaneto 
To have 0.1.7 working for us without errors, we removed check 11 (Check compatible shapes for given platform image ocid) from compute.tf. This check only has the most recent images.
With this code removed, we can use platform image OCID in 0.1.7.

**Comment by andrecorreaneto** [comment]
Hello @ervreugdenhil ,
The check is now disabled in 0.1.8.
Thanks.
